export const DEFAULTS = {
    main: {
        fontFamily: 'system-ui, "Segoe UI", Roboto, Arial, sans-serif',
        fontSizePx: 56,
        lineHeight: 1.42,
        weight: 500,
        letterSpacingEm: 0.01,
        wordSpacingEm: 0.02,
        color: '#e5e7eb',
        background: '#0b0f14',
        maxLineWidthCh: 60,
        dimOthers: 0.25,
    },
    display: {
        fontFamily: 'system-ui, "Segoe UI", Roboto, Arial, sans-serif',
        fontSizePx: 64,
        lineHeight: 1.4,
        weight: 600,
        letterSpacingEm: 0.00,
        wordSpacingEm: 0.02,
        color: '#f3f4f6',
        background: '#05080c',
        maxLineWidthCh: 62,
        dimOthers: 0.2,
    },
};
